CREATE TABLE widget_variant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    widget_id    BIGINT                                  NOT NULL,
    color_id     BIGINT,
    metrics_id   BIGINT,
    variant_name VARCHAR(255),
    image_url    VARCHAR(255),
    price        INTEGER                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_widget_variant PRIMARY KEY (id)
);

ALTER TABLE widget_variant
    ADD CONSTRAINT FK_WIDGET_VARIANT_ON_COLOR FOREIGN KEY (color_id) REFERENCES color (color_id);

ALTER TABLE widget_variant
    ADD CONSTRAINT FK_WIDGET_VARIANT_ON_METRICS FOREIGN KEY (metrics_id) REFERENCES widget_metrics (widget_metrics_id);

ALTER TABLE widget_variant
    ADD CONSTRAINT FK_WIDGET_VARIANT_ON_WIDGET FOREIGN KEY (widget_id) REFERENCES widget (id);