CREATE TABLE widget
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype       VARCHAR(31)                             NOT NULL,
    widget_name VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    blurb       TEXT                                    NOT NULL,
    image_url   VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_widget PRIMARY KEY (id)
);

ALTER TABLE widget
    ADD CONSTRAINT uc_widget_slug UNIQUE (slug);