CREATE TABLE color
(
    color_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color_code  VARCHAR(255)                            NOT NULL,
    color_label VARCHAR(255)                            NOT NULL,
    color_hex   VARCHAR(7)                              NOT NULL,
    CONSTRAINT pk_color PRIMARY KEY (color_id)
);